config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :products
  resources :brands
  resources :products do 
  resources :reviews
  end
  resources :locations
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, only: [:index, :show]

  resources :ratings, only: :update


end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    
    @brand = Brand.find(params[:id])
    @products = @brand.products
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :logo)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_brand.html.erb
<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="thumbnail">
    <%= link_to image_tag(brand.logo_url, {style: "height: 100px;"}), brand.url %>
    <div class="caption">    
      <h3><%= link_to truncate(brand.name, length: 15),  brand %></h3>
      <p><%= truncate(brand.description, length: 30) %></p>
      <p><%= link_to 'View', brand.url, class: "btn btn-default" %></p>
    </div>
  </div>
</div>

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_area :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h4>Editing Brand</h4>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<h4>Brands</h4>

<div class="row clearfix">
  <%= render @brands %>
</div>

<%= link_to 'New Brand', new_brand_path %>
<%= link_to("products", products_path) %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<p>
  <strong>Logo:</strong>
  <%= image_tag @brand.logo_url %>
</p>

<ul>
  <% @brand.products.each  do |product| %>
    <li><%= image_tag(product.image) %></li>
    <li><%= product.name %></li>
    <li><%= product.description  %></li>
    <li><%= product.image %></li>
    <li><%= product.price_retail %></li>  
  <% end %>
</ul>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>