config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :products
  resources :brands
  resources :products do 
  resources :reviews
  end
  resources :locations
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, only: [:index, :show]

  resources :ratings, only: :update


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_product

  def index
    @reviews = Review.all
  end

  def show
  end

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = current_user.reviews.new(review_params)
    @review.product = @product

    respond_to do |format|
      if @review.save
        format.html { redirect_to @product, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @product, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to @product, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_product
      @product = Product.find(params[:product_id])
    end

    def review_params
      params.require(:review).permit(:user_id, :product_id, :description)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<fieldset>
  <%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    
    <div class="actions">
      <%= f.submit class: "btn btn-default" %>
    </div>
  <% end %>
</fieldset>

app/views/reviews/_review.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to review.user do %>
      <%= image_tag review.user.image, class: "media-object user-image" %>
    <% end %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= time_ago_in_words review.created_at %> ago </h4>
    <p><%= review.description %></p>
  </div>
</div>

app/views/reviews/edit.html.erb
<h4>Editing Review</h4>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing Reviews</h1>
<ul>
  <% @reviews.each  do |review| %>
  <li> 
    <p class="user-name"></p> 
    <p><%= image_tag review.user.image %></p>
    <p><%= review.product.name %></p>
    <p><%= review.description %></p>
    <p><%= review.created_at %></p>
    <p><%= link_to "view product", review.product %></p>
  </li>
  <% end %>
</ul> 

<br>

<%= link_to 'New Review', new_product_review_path(@product) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product_id %>
</p>

<p>
  <strong>Review date:</strong>
  <%= @review.created_at %>
</p>

<%= link_to 'Edit', edit_product_review_path(@product, @review) %> |
<%= link_to 'Back', product_reviews_path(@product) %>