config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :products
  resources :brands
  resources :products do 
  resources :reviews
  end
  resources :locations
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, only: [:index, :show]

  resources :ratings, only: :update


end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "GoodLook", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Browse <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Products", products_path %></li>
            <li><%= link_to "Brands", brands_path %></li>
            <li><%= link_to "Map", locations_path %></li>
            <li><%= link_to "Users", users_path %></li>
          </ul>                     
        </li>
        <% if user_signed_in? %>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Edit", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
      <%= search_form_for @search, class: "navbar-form navbar-left" do |f|%>
        <div class="form-group">
          <%= f.text_field :name_cont, class: "form-control", placeholder: "Search" %> 
        </div>
        <%= f.submit "Search", class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_location_search.html.erb
<h4>Search Locations</h4> 
<div class="form-group">
  <%= form_tag locations_path, :method => :get do %>  
    <div class="form-group">
      <%= text_field_tag :search, params[:search], class: "form-control" %>
    </div>
    <%= submit_tag "Search Near", :name => nil, class: "btn btn-default" %>  
<% end %>  
</div>

app/views/layouts/_search.html.erb
<div class="form-group">
  <h2 class="advanced-search">Click for Advanced Search</h2>
  <%= search_form_for @search do |f|%>
    <%= f.condition_fields do |c|%>
    <div class="field">
      <%= c.attribute_fields do |a| %>
        <div class="form-group">
          <%= c.label "Filter Select" %>
          <%= a.attribute_select({associations: [:brand]}, { class: "form-control"}) %>
        </div>
      <% end %>

      <div class="form-group">
        <%= c.label "Predicate Select" %>
        <%= c.predicate_select({}, {class: "form-control"}) %>
      </div>
      
      <%= c.value_fields do |v| %>
        <div class="form-group">
          <%= c.label "Search" %>
          <%= v.text_field :value, class: "form-control" %> 
        </div>
      <% end %>
    </div>
    <% end %>
    <div class="actions">
      <%= f.submit "Search", class: "btn btn-default" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LookgoodFeelgood</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
  <body>
  
    <div class="container">
      <main class="clearfix">
        <%= render "layouts/header" %>
        <%= yield %>
      </main>
      <footer>
        <p>&copy; Christabel Samuels 2015</p>
      </footer> 
    </div>
</body>
</html>